name: Build Assets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Assets (CSS and JavaScript)
      run: npm run build

    - name: Commit compiled assets
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore: update compiled assets (CSS and JavaScript)"
        file_pattern: 'resources/styles/public/*.css resources/js/public/**/*'
